### ISSUE TITLE
Move affiliation from below to above the table of contents (toc)

### ISSUE THREAD

**Issue by joundso** [kapsner/authors-block#1]
Minor detail: If a table of contents is rendered, the affiliations are currently below it. For simplicity, however, I would expect the affiliations to be between the author names and (above) the table of contents.

Regardless: Many thanks for this awesome template!

**Comment by joundso** [comment]
Using this `_quarto.yml`:
```yaml
---
title: "Authors-block Example"

authors:
  - name: John Doe
    affiliations:
      - ref: jdct
    corresponding: true
    email: john.doe@jdct.edu
    orcid: 0000-1111-2222-3333
    equal-contributor: true
  - name: John Roe
    affiliations:
      - ref: jdct
    orcid: 0000-3333-2222-1111
  - name: Jane Roe
    affiliations:
      - ref: jdct
      - ref: iot
    orcid: 0000-2222-1111-3333
    equal-contributor: true

affiliations:
  - id: jdct
    name: John Doe Center for Technology, John Doe University, Doetown, Germany.
  - id: iot
    name: Institute of Technology, John Doe University, Doetown, Germany.

filters:
  - authors-block

format:
  #native: default
  docx:
    toc: true
  pdf: default
---

# Brings Quarto's Standardized Authors- & Affiliations-Block to docx-Documents

## Heading 2

Demo text.
```

Produces this output (with the affiliation below the table of contents):
![grafik](https://user-images.githubusercontent.com/56686638/208094701-ffb0cb0d-0a55-4a58-af10-8cf6ee404cae.png)
