### ISSUE TITLE
Using one author only breaks rendering

### ISSUE THREAD

**Issue by joundso** [kapsner/authors-block#2]
Using the [example.qmd](https://github.com/kapsner/authors-block/blob/997e605ecea203fb391de1684147fbfa5fa1944c/example.qmd) and simply removing the second and third author (and `orcid` and `equal-contributor: true`), the complete header (title + author information) in the rendered documents is missing:

```yaml
---
title: "Authors-block Example"

authors:
  - name: John Doe
    affiliations:
      - ref: jdct
    corresponding: true
    email: john.doe@jdct.edu


affiliations:
  - id: jdct
    name: John Doe Center for Technology, John Doe University, Doetown, Germany.


filters:
  - authors-block

format:
  #native: default
  docx: default
  pdf: default
---

## Brings Quarto's Standardized Authors- & Affiliations-Block to docx-Documents
```

yields to
![grafik](https://user-images.githubusercontent.com/56686638/208100934-5d740d70-a800-49d6-b926-2179e64e5f06.png)

instead of
![grafik](https://user-images.githubusercontent.com/56686638/208101535-6ef7e7de-0b13-4fec-892d-c1502d7512ea.png)
(unfortunately I do not have a code for this, but have edited the Word document manually)

**Comment by kapsner** [comment]
Hi @joundso , thanks for this nice catch. I was able to reproduce the error using your example from above. However, (and I have no idea why this happens) the error does not occur on my system when removing the double empty lines before "affiliations" and "filters" in the YAML header.

With the following YAML header, I get your example working without a problem:
```yaml
---
title: "Authors-block Example"

authors:
  - name: John Doe
    affiliations:
      - ref: jdct
    corresponding: true
    email: john.doe@jdct.edu

affiliations:
  - id: jdct
    name: John Doe C.enter for Technology, John Doe University, Doetown, Germany.

filters:
  - authors-block

format:
  docx: default
  pdf: default
---
```

Pls check if this fixes your error as well.

**Comment by kapsner** [comment]
Could be related to https://github.com/quarto-dev/quarto-cli/issues/3560

**Comment by kapsner** [comment]
I've investigated this a little further. Indeed, the issue seems not to be related to the authors-block extension, as it also occurs when not using it. 

Introducing 2 empty lines in the YAML-Header breaks the rendering of the header in the specified document, so to me this seems clearly to be associated with the issue described [here](https://github.com/quarto-dev/quarto-cli/issues/3560).

```yaml
---
title: "Authors-block Example"

authors:
  - name: John Doe
    affiliations:
      - ref: jdct
    corresponding: true
    email: john.doe@jdct.edu
    orcid: 0000-1111-2222-3333
    equal-contributor: true
  - name: John Roe
    affiliations:
      - ref: jdct
    orcid: 0000-3333-2222-1111
  - name: Jane Roe
    affiliations:
      - ref: jdct
      - ref: iot
    orcid: 0000-2222-1111-3333
    equal-contributor: true


affiliations:
  - id: jdct
    name: John Doe Center for Technology, John Doe University, Doetown, Germany.
  - id: iot
    name: Institute of Technology, John Doe University, Doetown, Germany.

format:
  pdf: default
---
```
