### ISSUE TITLE
Equal contribution for last authors

### ISSUE THREAD

**Issue by PierreSolomon** [kapsner/authors-block#3]
Hello,

Is there a way to indicate an equal contribution for the last authors? From the example, I can see that we could do it for the first authors (the ones that write the papers) but I can't see how to do it for the last authors (the ones that direct the work). I previously so papers indicating that the last two authors directed the work equaly so I think it would be nice to have this feature.

**Comment by kapsner** [comment]
Is this what you are looking for?

![image](https://user-images.githubusercontent.com/44973495/211895964-8e3c639d-da44-41f9-a404-6488474bc0a7.png)


```yml
---
title: "Authors-block Example"

authors:
  - name: John Doe
    affiliations:
      - ref: jdct
    corresponding: true
    email: john.doe@jdct.edu
    orcid: 0000-1111-2222-3333
  - name: John Roe
    affiliations:
      - ref: jdct
    orcid: 0000-3333-2222-1111
    equal-contributor: true
  - name: Jane Roe
    affiliations:
      - ref: jdct
      - ref: iot
    orcid: 0000-2222-1111-3333
    equal-contributor: true

affiliations:
  - id: jdct
    name: John Doe Center for Technology, John Doe University, Doetown, Germany.
  - id: iot
    name: Institute of Technology, John Doe University, Doetown, Germany.

filters:
- authors-block

format:
  docx: default
  #native: default
---
```
