### ISSUE TITLE
Only affiliation's name field is rendered.

### ISSUE THREAD

**Issue by sebastianrowan** [kapsner/authors-block#9]
In my document, I am using the more complex data structure for the affiliation field like this:

```
affiliations:
  - name: Sebastian Rowan
    orcid: 0000-0000-0000-0000
    email: e@mail.com
    affiliations:
      - id: unh
        name: University of New Hampshire
        department: Civil Engineering
        city: Durham
        state: NH
        country: USA
        postal-code: 03824
```

And when rendering the file to docx, the affiliation only shows "University of New Hampshire" like this:

![image](https://github.com/kapsner/authors-block/assets/79868066/45032653-a153-476a-a1a6-f338705bbe74)

I would prefer to keep the long-form for the affiliations if possible. Is there a way to do this and get them to render properly?
